### ISSUE TITLE
Consider importing to 'Plugins/Editor' folder

### ISSUE THREAD

**Issue by TarasOsiris** [PhannGor/unity3d-rainbow-folders#20]
This gives some compilation time benefits as described [here](https://medium.com/@darrentsung/the-clocks-ticking-how-to-optimize-compile-time-in-unity-45d1f200572b#.2nlzgqwqp).

> To reduce the amount of time it takes to recompile, you can use special folders that Unity compiles into a separate .dll called Assembly-CSharp-firstpass.dll. The key part is that code in this .dll won’t recompile if you don’t change it. These special folders are named Plugins and Standard Assets and must exist on the top-level directory under Assets.

**Comment by iivok** [comment]
I'd love to use this asset, but can't since it relies on the Editor Default Resources folder which must be located at the root level under Assets.

A better way would be to have a RainbowFolders/Editor/Resources folder that contains the assets the editor scripts need to load dynamically. The path could be sniffed dynamically (for example by looking for RainbowFolders folder), so I could place it anywhere. 

Additionally, if placed under Plugins, I think Plugins/RainbowFolders/Editor is better than Plugins/Editor/RainbowFolders for movability.

**Comment by Indiefreaks** [comment]
I'm all for it.
I just downloaded it and thought to myself that it would be less invasive in my project if it was somehow under a plugins folder.

**Comment by TarasOsiris** [comment]
@iivok Plugins/Editor/RainbowFolders looks better to me because I keep all 'Editor' plugins under 'Plugins/Editor'. e.g. 'Plugins/Editor/RainbowFolders', 'Plugins/Editor/QHierarchy', so that it is clear which ones are editor-only plugins.

**Comment by Borod4r** [comment]
We got rid of the "Editor Default Resources" folder and you can freely move "Rainbow Folders" wherever you want in your project. Looks like I can close this issue now ;)
